### PR TITLE
Distinguish pulsar errors with codes and messages from Result.h

### PR DESCRIPTION
**Pull request by rwstauner**

### CODE REVIEW

**Comment by rwstauner** [comment]
If you have any pointers about how i could write tests for this i'd be glad to add them.

**Comment by rwstauner** [comment]
```
[2] pry(main)> c.create_producer("non-persistent://t/n/foo")
Pulsar::Error::ConnectError: Failed to connect to broker
[3] pry(main)>
```

**Comment by rwstauner** [comment]
hacked together a test suite... let me know if you have a better suggestion for doing that.

**Comment by rwstauner** [comment]
Seeing stuff like this in sentry now:

> Pulsar::Error::ServiceUnitNotReady
Service Unit unloaded between client did lookup and producer/consumer got created

so nice. ♥

**Comment by atezs82** [comment]
Is the list of errors in sync with Pulsar 2.6.1 (we use that now). If it is, I have no problems with merging this, thanks for the change!

**Comment by rwstauner** [comment]
I believe so.  It looks like they have only appended a few new Results to the end of the enum list since then.

**Comment by atezs82** [comment]
Do you see any value in adding those results to this patchset?

**Comment by rwstauner** [comment]
Sure, I appended the 4 new results to this PR.
Since there aren't any github checks I recommend pulling down this PR and ensuring you can run the tests.

**Comment by atezs82** [comment]
Thank you!

**Comment by atezs82** [comment]
Test run (`rake spec`) is failing with these issues (there are a number of them, I think one for each constant added):
```
1) pulsar ext errors inherits from Pulsar::Error
     Failure/Error: expect(Pulsar::Error::UnknownError.new.is_a?(Pulsar::Error)).to be true

     NameError:
       uninitialized constant Pulsar::Error::UnknownError
     # ./spec/pulsar/ext_spec.rb:38:in `block (3 levels) in <top (required)>'
```
Will have to take a look, it might be that I was doing something wrong here.

**Comment by rwstauner** [comment]
it might be that you have to remove old build files and recompile.

**Pull request merged**
