### PR TITLE
Update Gemfile.lock

### PR DESCRIPTION
**Pull request by rwstauner**
Bundler desperately wants to update the lock file.

### CODE REVIEW

**Comment by addisonj** [comment]
We should also update this to be a newer version of the pulsar-client, latest is now 2.5.2

**Comment by addisonj** [comment]
We may want to consider just bumping this client version to 2.5.2, as it has some fixes in C++ library and that is what are clusters are running at

**Comment by atezs82** [comment]
Since we have already updated, clusters are running with the official version of Pulsar 2.6.1. We might want to upgrade this version as well.

**Comment by rwstauner** [comment]
This change is simply what bundler producers when i run "install" locally.
On the latest master I get the same result.
If you want to change the version of `+    pulsar-client (2.4.1.pre.beta.4)` it doesn't actually relate to the C++ being built against, we just need to update `lib/pulsar/client/version.rb`

**Comment by rwstauner** [comment]
I updated the version

**Review by atezs82 — APPROVED** [review]

**Comment by rwstauner** [comment]
Gemfile.lock was updated in #15

**Pull request closed without merging**
